-- Fresh DEVELOPMENT projects only. Never run this baseline against production.
-- Schema captured read-only from cxtsnupbfqqosvzhwqyw on 2026-09-06.
-- No production users, messages, quiz history, credentials or storage objects.
SET search_path = public, extensions;
CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;
CREATE TYPE public.bloom_level_enum AS ENUM ('0_unseen','1_remember','2_understand','3_apply','4_analyze');
CREATE SEQUENCE public.music_id_seq;

CREATE TABLE public."events" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "title" text NOT NULL,
  "description" text,
  "start_time" timestamp with time zone NOT NULL,
  "end_time" timestamp with time zone,
  "location" text,
  "url" text NOT NULL,
  "category" text,
  "scraped_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  "embedding" vector(384)
);

CREATE TABLE public."messages" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "session_id" uuid NOT NULL,
  "role" text NOT NULL,
  "content" text NOT NULL,
  "metadata" jsonb DEFAULT '{}'::jsonb,
  "created_at" timestamp with time zone DEFAULT now(),
  "response_for" uuid,
  "is_summary" boolean NOT NULL,
  "has_been_summarised" boolean DEFAULT false
);

CREATE TABLE public."music" (
  "id" bigint DEFAULT nextval('music_id_seq'::regclass) NOT NULL,
  "name" text NOT NULL,
  "ragam_name" text,
  "artist" text,
  "performance_type" text,
  "description" text,
  "lyrics" text,
  "audio_url" text,
  "sheet_music_url" text,
  "duration" integer,
  "tempo" text,
  "tala" text,
  "raga_characteristics" text,
  "emotional_context" text,
  "associated_characters" text[],
  "metadata" jsonb,
  "embedding" vector(384),
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now()
);

CREATE TABLE public."ornaments" (
  "id" text NOT NULL,
  "name" text NOT NULL,
  "path_d" text NOT NULL,
  "tooltip_position" jsonb NOT NULL,
  "description" text NOT NULL,
  "image_url" text,
  "metadata" jsonb,
  "embedding" vector(384),
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now()
);

CREATE TABLE public."quiz_question" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "quiz_id" uuid NOT NULL,
  "display_id" integer,
  "concept_id" character varying(255) NOT NULL,
  "target_level" bloom_level_enum NOT NULL,
  "misconception_target" boolean DEFAULT false NOT NULL,
  "question" text NOT NULL,
  "options" jsonb NOT NULL,
  "correct_answer" text NOT NULL,
  "explanation" text,
  "distractor_map" jsonb,
  "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "sequence_no" integer,
  "selected_answer" text,
  "is_correct" boolean,
  "response_ms" integer,
  "answered_at" timestamp with time zone
);

CREATE TABLE public."quiz_session" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "user_id" character varying(255) NOT NULL,
  "source" text DEFAULT 'adaptive'::text NOT NULL,
  "selected_concepts" jsonb,
  "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "submitted_at" timestamp with time zone,
  "policy_version" text,
  "session_state" jsonb,
  "status" text DEFAULT 'active'::text NOT NULL
);

CREATE TABLE public."sessions" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid,
  "title" text DEFAULT 'New Conversation'::text,
  "created_at" timestamp with time zone DEFAULT now()
);

CREATE TABLE public."user_proficiency_state" (
  "user_id" character varying(255) NOT NULL,
  "node_id" character varying(255) NOT NULL,
  "bloom_level" bloom_level_enum DEFAULT '0_unseen'::bloom_level_enum NOT NULL,
  "misconception_flag" boolean DEFAULT false,
  "last_evidence" text,
  "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "last_reasoning" text,
  "last_confidence" double precision
);

ALTER SEQUENCE public.music_id_seq OWNED BY public.music.id;
ALTER TABLE public."events" ADD CONSTRAINT "events_pkey" PRIMARY KEY (id);
ALTER TABLE public."events" ADD CONSTRAINT "events_url_key" UNIQUE (url);
ALTER TABLE public."messages" ADD CONSTRAINT "messages_pkey" PRIMARY KEY (id);
ALTER TABLE public."messages" ADD CONSTRAINT "messages_role_check" CHECK ((role = ANY (ARRAY['system'::text, 'user'::text, 'assistant'::text])));
ALTER TABLE public."music" ADD CONSTRAINT "music_pkey" PRIMARY KEY (id);
ALTER TABLE public."ornaments" ADD CONSTRAINT "ornaments_pkey" PRIMARY KEY (id);
ALTER TABLE public."quiz_question" ADD CONSTRAINT "quiz_question_pkey" PRIMARY KEY (id);
ALTER TABLE public."quiz_session" ADD CONSTRAINT "quiz_session_pkey" PRIMARY KEY (id);
ALTER TABLE public."sessions" ADD CONSTRAINT "sessions_pkey" PRIMARY KEY (id);
ALTER TABLE public."user_proficiency_state" ADD CONSTRAINT "user_proficiency_state_pkey" PRIMARY KEY (user_id, node_id);
ALTER TABLE public."messages" ADD CONSTRAINT "fk_messages_response_for" FOREIGN KEY (response_for) REFERENCES messages(id) ON DELETE CASCADE;
ALTER TABLE public."messages" ADD CONSTRAINT "messages_session_id_fkey" FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE;
ALTER TABLE public."quiz_question" ADD CONSTRAINT "quiz_question_quiz_id_fkey" FOREIGN KEY (quiz_id) REFERENCES quiz_session(id) ON DELETE CASCADE;
ALTER TABLE public."sessions" ADD CONSTRAINT "sessions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id);
CREATE INDEX events_start_time_idx ON public.events USING btree (start_time);
CREATE INDEX events_embedding_idx ON public.events USING ivfflat (embedding vector_cosine_ops) WITH (lists='100');
CREATE INDEX idx_quiz_session_user_id ON public.quiz_session USING btree (user_id);
CREATE INDEX idx_quiz_session_created_at ON public.quiz_session USING btree (created_at);
CREATE UNIQUE INDEX idx_quiz_question_sequence ON public.quiz_question USING btree (quiz_id, sequence_no) WHERE (sequence_no IS NOT NULL);
CREATE INDEX idx_quiz_question_quiz_id ON public.quiz_question USING btree (quiz_id);
CREATE INDEX idx_quiz_question_concept_id ON public.quiz_question USING btree (concept_id);
CREATE INDEX idx_user_proficiency_user_id ON public.user_proficiency_state USING btree (user_id);
CREATE INDEX idx_user_proficiency_node_id ON public.user_proficiency_state USING btree (node_id);
CREATE INDEX idx_user_proficiency_bloom_level ON public.user_proficiency_state USING btree (bloom_level);
CREATE INDEX idx_user_proficiency_misconception ON public.user_proficiency_state USING btree (misconception_flag) WHERE (misconception_flag = true);
CREATE INDEX idx_user_proficiency_updated_at ON public.user_proficiency_state USING btree (updated_at);
CREATE INDEX idx_ornaments_name ON public.ornaments USING btree (name);
CREATE INDEX idx_ornaments_embedding ON public.ornaments USING ivfflat (embedding vector_cosine_ops);
CREATE INDEX idx_ornaments_search ON public.ornaments USING gin (to_tsvector('english'::regconfig, ((name || ' '::text) || description)));
CREATE INDEX idx_music_name ON public.music USING btree (name);
CREATE INDEX idx_music_ragam ON public.music USING btree (ragam_name);
CREATE INDEX idx_music_artist ON public.music USING btree (artist);
CREATE INDEX idx_music_embedding ON public.music USING ivfflat (embedding vector_cosine_ops);
CREATE INDEX idx_music_search ON public.music USING gin (to_tsvector('english'::regconfig, ((((((((((COALESCE(name, ''::text) || ' '::text) || COALESCE(ragam_name, ''::text)) || ' '::text) || COALESCE(artist, ''::text)) || ' '::text) || COALESCE(description, ''::text)) || ' '::text) || COALESCE(raga_characteristics, ''::text)) || ' '::text) || COALESCE(emotional_context, ''::text))));
CREATE INDEX idx_music_characters ON public.music USING gin (associated_characters);
CREATE INDEX idx_messages_has_been_summarised ON public.messages USING btree (has_been_summarised);
CREATE INDEX idx_messages_session_id_created_at ON public.messages USING btree (session_id, created_at);
CREATE INDEX idx_messages_response_for ON public.messages USING btree (response_for);

CREATE OR REPLACE FUNCTION public.update_user_proficiency_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.match_events(query_embedding vector, match_threshold double precision DEFAULT 0.5, match_count integer DEFAULT 5)
 RETURNS TABLE(id bigint, title text, description text, start_time timestamp with time zone, end_time timestamp with time zone, location text, url text, embedding vector, similarity double precision)
 LANGUAGE plpgsql
AS $function$
BEGIN
  RETURN QUERY
  SELECT
    events.id,
    events.title,
    events.description,
    events.start_time,
    events.end_time,
    events.location,
    events.url,
    events.embedding,
    (1 - (events.embedding <=> query_embedding))::float as similarity
  FROM events
  WHERE events.embedding IS NOT NULL
    AND 1 - (events.embedding <=> query_embedding) > match_threshold
  ORDER BY events.embedding <=> query_embedding
  LIMIT match_count;
END;
$function$;

CREATE OR REPLACE FUNCTION public.match_music(query_embedding vector, match_threshold double precision, match_count integer)
 RETURNS TABLE(id bigint, name text, ragam_name text, artist text, performance_type text, description text, lyrics text, audio_url text, sheet_music_url text, duration integer, tempo text, tala text, raga_characteristics text, emotional_context text, associated_characters text[], metadata jsonb, similarity double precision)
 LANGUAGE sql
 STABLE
AS $function$
  SELECT
    music.id,
    music.name,
    music.ragam_name,
    music.artist,
    music.performance_type,
    music.description,
    music.lyrics,
    music.audio_url,
    music.sheet_music_url,
    music.duration,
    music.tempo,
    music.tala,
    music.raga_characteristics,
    music.emotional_context,
    music.associated_characters,
    music.metadata,
    1 - (music.embedding <=> query_embedding) AS similarity
  FROM music
  WHERE music.embedding IS NOT NULL
  AND 1 - (music.embedding <=> query_embedding) > match_threshold
  ORDER BY music.embedding <=> query_embedding
  LIMIT match_count;
$function$;

CREATE OR REPLACE FUNCTION public.match_ornaments(query_embedding vector, match_threshold double precision, match_count integer)
 RETURNS TABLE(id text, name text, path_d text, tooltip_position jsonb, description text, image_url text, metadata jsonb, similarity double precision)
 LANGUAGE sql
 STABLE
AS $function$
  SELECT
    ornaments.id,
    ornaments.name,
    ornaments.path_d,
    ornaments.tooltip_position,
    ornaments.description,
    ornaments.image_url,
    ornaments.metadata,
    1 - (ornaments.embedding <=> query_embedding) AS similarity
  FROM ornaments
  WHERE ornaments.embedding IS NOT NULL
  AND 1 - (ornaments.embedding <=> query_embedding) > match_threshold
  ORDER BY ornaments.embedding <=> query_embedding
  LIMIT match_count;
$function$;

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$function$;
CREATE TRIGGER update_ornaments_updated_at BEFORE UPDATE ON public.ornaments FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_music_updated_at BEFORE UPDATE ON public.music FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_user_proficiency_updated_at BEFORE UPDATE ON public.user_proficiency_state FOR EACH ROW EXECUTE FUNCTION update_user_proficiency_updated_at();
ALTER TABLE public."events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."quiz_session" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."quiz_question" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."user_proficiency_state" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."ornaments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."music" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."sessions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."messages" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access to events" ON public."events" AS PERMISSIVE FOR SELECT TO "public" USING (true);
CREATE POLICY "Users can insert their own quizzes" ON public."quiz_session" AS PERMISSIVE FOR INSERT TO "public" WITH CHECK (((auth.uid())::text = (user_id)::text));
CREATE POLICY "Users can update their own quizzes" ON public."quiz_session" AS PERMISSIVE FOR UPDATE TO "public" USING (((auth.uid())::text = (user_id)::text));
CREATE POLICY "Users can view their own quizzes" ON public."quiz_session" AS PERMISSIVE FOR SELECT TO "public" USING (((auth.uid())::text = (user_id)::text));
CREATE POLICY "Users can insert questions for their quizzes" ON public."quiz_question" AS PERMISSIVE FOR INSERT TO "public" WITH CHECK ((EXISTS ( SELECT 1
   FROM quiz_session s
  WHERE ((s.id = quiz_question.quiz_id) AND ((s.user_id)::text = (auth.uid())::text)))));
CREATE POLICY "Users can update questions for their quizzes" ON public."quiz_question" AS PERMISSIVE FOR UPDATE TO "public" USING ((EXISTS ( SELECT 1
   FROM quiz_session s
  WHERE ((s.id = quiz_question.quiz_id) AND ((s.user_id)::text = (auth.uid())::text)))));
CREATE POLICY "Users can view their own quiz questions" ON public."quiz_question" AS PERMISSIVE FOR SELECT TO "public" USING ((EXISTS ( SELECT 1
   FROM quiz_session s
  WHERE ((s.id = quiz_question.quiz_id) AND ((s.user_id)::text = (auth.uid())::text)))));
CREATE POLICY "Users can insert their own proficiency" ON public."user_proficiency_state" AS PERMISSIVE FOR INSERT TO "public" WITH CHECK (((auth.uid())::text = (user_id)::text));
CREATE POLICY "Users can update their own proficiency" ON public."user_proficiency_state" AS PERMISSIVE FOR UPDATE TO "public" USING (((auth.uid())::text = (user_id)::text));
CREATE POLICY "Users can view their own proficiency" ON public."user_proficiency_state" AS PERMISSIVE FOR SELECT TO "public" USING (((auth.uid())::text = (user_id)::text));
CREATE POLICY "Users can manage their own sessions" ON public."sessions" AS PERMISSIVE FOR ALL TO "public" USING ((((auth.uid() IS NOT NULL) AND (auth.uid() = user_id)) OR ((auth.uid() IS NULL) AND (user_id IS NULL))));
CREATE POLICY "Users can manage their own messages" ON public."messages" AS PERMISSIVE FOR ALL TO "public" USING ((EXISTS ( SELECT 1
   FROM sessions
  WHERE ((sessions.id = messages.session_id) AND (((auth.uid() IS NOT NULL) AND (sessions.user_id = auth.uid())) OR ((auth.uid() IS NULL) AND (sessions.user_id IS NULL)))))));

-- Development baseline deliberately limits content writes to the backend service role.
CREATE POLICY "Public read music" ON public.music FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Public read ornaments" ON public.ornaments FOR SELECT TO anon, authenticated USING (true);
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
